[workspace]
resolver = "2"
members = [
    "blockchain/core",
    "blockchain/node-std",
    "blockchain/node-no-std",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Vinicius Cruz"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
sha2 = { version = "0.10", default-features = false }
